# CMake generated Testfile for 
# Source directory: /home/gse5/catkin_ws/cartographer_ws/src/jackal_desktop/jackal_viz
# Build directory: /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_jackal_viz_roslaunch-check_launch_view_model.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/test_results/jackal_viz/roslaunch-check_launch_view_model.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/test_results/jackal_viz" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/test_results/jackal_viz/roslaunch-check_launch_view_model.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal_desktop/jackal_viz/launch/view_model.launch' ")
add_test(_ctest_jackal_viz_roslaunch-check_launch_view_robot.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/test_results/jackal_viz/roslaunch-check_launch_view_robot.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/test_results/jackal_viz" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_viz/test_results/jackal_viz/roslaunch-check_launch_view_robot.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal_desktop/jackal_viz/launch/view_robot.launch' ")
subdirs("gtest")
