# CMake generated Testfile for 
# Source directory: /home/gse5/catkin_ws/cartographer_ws/src/jackal/jackal_navigation
# Build directory: /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_jackal_navigation_roslaunch-check_launch_include_amcl.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_include_amcl.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_include_amcl.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal/jackal_navigation/launch/include/amcl.launch' ")
add_test(_ctest_jackal_navigation_roslaunch-check_launch_amcl_demo.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_amcl_demo.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_amcl_demo.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal/jackal_navigation/launch/amcl_demo.launch' ")
add_test(_ctest_jackal_navigation_roslaunch-check_launch_include_gmapping.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_include_gmapping.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_include_gmapping.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal/jackal_navigation/launch/include/gmapping.launch' ")
add_test(_ctest_jackal_navigation_roslaunch-check_launch_gmapping_demo.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_gmapping_demo.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_gmapping_demo.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal/jackal_navigation/launch/gmapping_demo.launch' ")
add_test(_ctest_jackal_navigation_roslaunch-check_launch_include_move_base.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_include_move_base.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_include_move_base.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal/jackal_navigation/launch/include/move_base.launch' ")
add_test(_ctest_jackal_navigation_roslaunch-check_launch_odom_navigation_demo.launch "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_odom_navigation_demo.launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/gse5/catkin_ws/cartographer_ws/build_isolated/jackal_navigation/test_results/jackal_navigation/roslaunch-check_launch_odom_navigation_demo.launch.xml' '/home/gse5/catkin_ws/cartographer_ws/src/jackal/jackal_navigation/launch/odom_navigation_demo.launch' ")
subdirs("gtest")
