set(_CATKIN_CURRENT_PACKAGE "jackal_cartographer_navigation")
set(jackal_cartographer_navigation_VERSION "0.0.0")
set(jackal_cartographer_navigation_MAINTAINER "Aditya Bhattacharjee <abhattacharjee@clearpathrobotics.com>")
set(jackal_cartographer_navigation_PACKAGE_FORMAT "1")
set(jackal_cartographer_navigation_BUILD_DEPENDS "roslaunch")
set(jackal_cartographer_navigation_BUILD_EXPORT_DEPENDS "map_server" "move_base" "urdf" "xacro")
set(jackal_cartographer_navigation_BUILDTOOL_DEPENDS "catkin")
set(jackal_cartographer_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(jackal_cartographer_navigation_EXEC_DEPENDS "map_server" "move_base" "urdf" "xacro")
set(jackal_cartographer_navigation_RUN_DEPENDS "map_server" "move_base" "urdf" "xacro")
set(jackal_cartographer_navigation_TEST_DEPENDS )
set(jackal_cartographer_navigation_DOC_DEPENDS )
set(jackal_cartographer_navigation_URL_WEBSITE "")
set(jackal_cartographer_navigation_URL_BUGTRACKER "")
set(jackal_cartographer_navigation_URL_REPOSITORY "")
set(jackal_cartographer_navigation_DEPRECATED "")